### ISSUE TITLE
Always reports "No signature expected"

### ISSUE THREAD

**Issue by rugk** [tasn/webext-signed-pages#11]
![grafik](https://user-images.githubusercontent.com/11966684/36269910-b309a928-127a-11e8-88ef-49c01ff36082.png)

Firefox 58

**Comment by rugk** [comment]
I think your website is broken. Where the signature should be, it shows `
%%%SIGNED_PAGES_PGP_SIGNATURE%%%` on the bad website.

**Comment by tasn** [comment]
What's the URL you're accessing?

**Comment by rugk** [comment]
I can reproduce it with all of your example ones linked, but https://stosb.com/%7Etom/signed-pages/bad.html has this `%%%SIGNED_PAGES_PGP_SIGNATURE%%%` at the beginning in the source.

**Comment by rugk** [comment]
Ah wait I think I need to import the settings, first. 😄

**Comment by rugk** [comment]
Ah, works now.

**Comment by tasn** [comment]
:)
FWIW, I changed the bad.html file to include a more obviously bad signature rather than what was there at the moment.

**Comment by rugk** [comment]
Ah great, the previous thing looked like a template error or so…

**Comment by tasn** [comment]
Yeah, I agree, thanks for pointing it out!
