### ISSUE TITLE
Breaks downloads

### ISSUE THREAD

**Issue by rugk** [tasn/webext-signed-pages#17]
I've been investigating a Firefox issue and it turned out your addon was causing it. If I have to guess, you somehow do not close/finish a request when it is cancelled or so…

So here are the full details, STR and so on: https://bugzilla.mozilla.org/show_bug.cgi?id=1480745

This is a very annoying minor bug that you'll get annoyed about each time you see it. :smile:

**Comment by tasn** [comment]
Thanks for reporting. I can't believe this is an issue with signed pages, it was annoying me too! :)

I'll try to figure it out, thanks for reporting!

**Comment by rugk** [comment]
Well… just disable the add-on and it works again, immediately. :laughing:

**Comment by tasn** [comment]
:broken_heart:

**Comment by rugk** [comment]
This is really critical, as I just noticed…
In Firefox 69.0.1 it often breaks long-running (or big file?) downloads and I get this error:
> /tmp/.../....part cannot be saved, because the source file cannot be read.

![](https://hostux.pics/images/2019/10/06/grafik8978e0acca3c978e.png)

Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1758895

**Comment by tasn** [comment]
Oh, thanks for the update!
Having just reviewed the code following your report there's indeed a problem. It seems like we just try to process and validate any "main_frame", though downloads (and icons?) can also be ones.
While reviewing the code I also spotted a few other issues:
1. ondata may be called more than once (e.g. partial data every time) - we need to address that.
2. We need to make sure the response is a utf-8 one rather than binary before we decide to process it - need to verify how this should be done exactly. This should fix this issue.

Are you able to consistently reproduce the download issue? If so, are you able to test a potential workaround?

**Comment by tasn** [comment]
Also, are you able to provide a link that fails? Or show the extension's output log? (Tools -> Web developer -> browser console)

**Comment by rugk** [comment]
Also maybe fix that TODO lol:
https://github.com/tasn/webext-signed-pages/blob/696d6d07399ee3be9f46722c5f98e8a823dab46f/src/background.js#L116

When the signature is not found, you can also add an if to return early instead of still decoding the text…

**Comment by rugk** [comment]
Maybe something like https://github.com/tasn/webext-signed-pages/pull/23??

**Comment by tasn** [comment]
From #23: Could you please try if this branch fixes it for you: https://github.com/tasn/webext-signed-pages/tree/early-abort

I added an early abort in case we shouldn't check a page.

**Comment by rugk** [comment]
Do you have a prebuild ZIP or so?

**Comment by tasn** [comment]
I can upload something, but it won't be signed so you won't be able to
install it. I can release a new version soon, as I already tested it myself
and at the very least there are no regressions.

**Comment by rugk** [comment]
Yeah, I can use `about:debugging`. That's easy…

**Comment by tasn** [comment]
Try this: [signed_pages-0.4.1.zip](https://github.com/tasn/webext-signed-pages/files/3708846/signed_pages-0.4.1.zip)

**Comment by rugk** [comment]
Hmm… could not reproduce the issue anymore right now… 🤔
But I guess it is fine… :wink:

**Comment by tasn** [comment]
Released a new version.
