### ISSUE TITLE
Sign git commits & releases

### ISSUE THREAD

**Issue by rugk** [tasn/webext-signed-pages#8]
This project is about signing web pages, but how can we trust the source here came from you (including the whether the bundled PGP keys, etc, are correct) and GitHub does not serve us modified stuff here. The solution is easy, IMHO, because git has a built-in solution:

You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/signing-commits-with-gpg/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases ([and here is a script for that](https://github.com/rugk/gittools/blob/master/signrelease.sh))

**Comment by tasn** [comment]
Releases are already signed (even uploaded my pubkey to github so they are also verified by github).
I don't like signing commits because it's a pain in the pass with rebasing, PRs and etc, so I avoid that, and it doesn't add much value over signing releases in the context of this project.

**Comment by rugk** [comment]
Ah okay, that is only displayed on the "tags" page. Maybe you could add some release notes (i.e. use GitHub's release feature) when creating a new release, later, so one can see that more prominently?

**Comment by tasn** [comment]
It's also displayed when you click on a release.
I'm not sure about the github release feature. Why don't they just get the text from the annotated tag? It seems like extra work for little benefit, as people who care about verifying releases should do so locally.
Happy to be convinced otherwise, it's just that at the moment, my workflow doesn't touch GitHub at all, I do everything from the command line, so I'm just looking for a good reason as to why do it differently.

Also, if I create the release from there it won't be signed, so I'm not sure about the workflow.

**Comment by rugk** [comment]
Yeah, don't ask me about GItHub's stuff… Maybe it's so that you can mark real releases/pre-releases and so on, when you also use tags for something else. I mean you can just copy and paste the text there again.And BTW, I did not even notice the release notes in the tags there on GitHub, as I just don't expand these tags usually…

> Also, if I create the release from there it won't be signed, so I'm not sure about the workflow.

You can create a release from an already existent tag, so that's easy. AFAIK it then does even prefill the release with the tag content.

**Comment by tasn** [comment]
I took a look at the UI, it doesn't populate the text when I click "add release notes".
There's also no button to do it form the releases tab or releases themselves (e.g. https://github.com/tasn/webext-signed-pages/releases/tag/v0.4.0) only from the tags page, which makes me very suspicious, thinking they may replace my tag with theirs. If not, it's very redundant, again for little benefit.
Another sensible approach would be to just get github correctly deal with annotated tags. It looks like they are mostly there, I wonder why they don't deal with it properly.

**Comment by rugk** [comment]
The GItHub release page, **does not create tags** when the tag already exists. (I think the UI makes it clear when you enter it.)

As said, the reason is maybe that some users use tags differently, and you may want to draft releases separately.

**Comment by tasn** [comment]
Even if it edits them, it's enough to break the signature, which is what I'm worried about here.

**Comment by rugk** [comment]
It does not do anything with them. The release things is completely **decoupled** from the tags. It's only that you, more or less, "attach" a release to a specific tag.

And of course they don't break signatures (they actually want to display them later on so that would be stupid), they do not do anything with git altogether there.

**Comment by tasn** [comment]
OK, I'll take a look, thanks.

**Comment by tasn** [comment]
Did it for the last few releases. Will try to remember doing it for future releases as well.
